services:
  linkedinfrontend:
    build:
      context: ./dev
      dockerfile: Dockerfile.fe
    ports:
      - "3000:3000"    
    depends_on:
      - db
  nodebackend: 
    build:
      context: ./server
      dockerfile: Dockerfile.be
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - linkedin_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
   linkedin_db:
